## Input & Output

### numpy 二进制文件

`save()`、`savez()`和`load()`函数以 numpy 专用的二进制类型（npy、npz）保存和读取数据，这三个函数会自动处理ndim、dtype、shape等信息，使用它们读写数组非常方便，但是`save()`输出的文件很难与其它语言编写的程序兼容。

npy格式：以二进制的方式存储文件，在二进制文件第一行以文本形式保存了数据的元信息（ndim，dtype，shape等），可以用二进制工具查看内容。

npz格式：以压缩打包的方式存储文件，可以用压缩软件解压。

* `numpy.save(file, arr, allow_pickle=True, fix_imports=True)` Save an array to a binary file in NumPy .npy format.

* `numpy.load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')` Load arrays or pickled objects from .npy, .npz or pickled files.

`np.loadtxt(filename,delimiter=',',skiprows=1,dtype=bytes,usecols=use_col_index_lst)`

* skiprows=1:跳过第一行

* usecols:指定列

### `np.where(condition)`

返回满足条件的下标。这里的坐标以tuple的形式给出，通常原数组有多少维，输出的tuple中就包含几个数组，分别对应符合条件元素的各维坐标。

In [1]:
import numpy as np
a = np.array([2,4,6,8,10])
np.where(a > 5)  # return index

(array([2, 3, 4]),)

In [2]:
a[np.where(a > 5)]

array([ 6,  8, 10])

In [5]:
b = np.arange(4).reshape(2,2)
b

array([[0, 1],
       [2, 3]])

In [7]:
np.where(b > 1)

(array([1, 1]), array([0, 1]))

In [8]:
a = np.arange(27).reshape(3,3,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [9]:
np.where(a > 5)

(array([0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2]),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [11]:
a[0][2][0]

6

In [12]:
a[0,2,1]

7

`np.where(condition, out_1, out_2)`:若满足condition，就返回out_1,否则返回out_2

In [13]:
aa = np.arange(10)
np.where(aa, 1, -1)  # 0为False,所以第一个输出-1

array([-1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [14]:
np.where(aa > 5, 1, -1)

array([-1, -1, -1, -1, -1, -1,  1,  1,  1,  1])