## 一、Numpy数组的合并与分割操作  
在机器学习算法中经常使用  

### 1.合并操作

In [1]:
import numpy as np
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([666, 666, 666])

In [17]:
x.shape, y.shape, z.shape

((3,), (3,), (3,))

In [3]:
np.concatenate([x, y])#default axis=0

array([1, 2, 3, 3, 2, 1])

In [4]:
np.concatenate([x, y, z])

array([  1,   2,   3,   3,   2,   1, 666, 666, 666])

上面为一维数组的拼接，接下来为二维的

In [5]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [6]:
A.shape

(2, 3)

In [11]:
res_0 = np.concatenate([A, A])

In [12]:
res_0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [13]:
res_0.shape

(4, 3)

In [14]:
res_1 = np.concatenate([A, A], axis=1)

In [16]:
res_1

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [15]:
res_1.shape

(2, 6)

那么，能不能把A和z拼接到一起呢？显然是不能的，因为z是1维数组，而A是2维数组，运行会报错。z.shape=(3,),此时我们就可以使用reshape操作将其先装换为2维数组，然后再进行拼接。

In [18]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

### np.vstack()

In [19]:
np.vstack([A, z])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

### np.hstack()

In [20]:
B = np.full((2, 2), 100)
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## numpy  
### 1.mat()和array()的区别
Numpy函数库中存在两种不同的数据类型（矩阵matrix和数组array），都可以用于处理行列表示的数字元素，虽然他们看起来很相似，但是在这两个数据类型上执行相同的数学运算可能得到不同的结果

In [1]:
import numpy as np
 
a = np.mat('1 3;5 7')
b = np.mat([[1,2],[3,4]])
print(a)
print(b)
print(type(a))
print(type(b))
c = np.array([[1,3],[4,5]])
print(c)
print(type(c))

[[1 3]
 [5 7]]
[[1 2]
 [3 4]]
<class 'numpy.matrix'>
<class 'numpy.matrix'>
[[1 3]
 [4 5]]
<class 'numpy.ndarray'>


首先，mat() 函数与array()函数生成矩阵所需的数据格式有区别，mat()函数中数据可以为字符串以分号（;）分割或者为列表形式以逗号（，）分割，而array()函数中数据只能为后者形式。

　　其次，两者的类型不同，用mat函数转换为矩阵后才能进行一些线性代数的操作。

In [2]:
from numpy import *
 
# 构建一个4*4的随机数组
array_1 = random.rand(4,4)
print(array_1)
print(type(array_1))

[[0.07371828 0.14299717 0.48366699 0.59851988]
 [0.42396133 0.1394344  0.4898589  0.74307941]
 [0.73498962 0.09622179 0.14326123 0.87234939]
 [0.26618049 0.50924503 0.65145571 0.4699903 ]]
<class 'numpy.ndarray'>


In [3]:
matrix_1 = mat(array_1)
print(matrix_1)
print(type(matrix_1))

[[0.07371828 0.14299717 0.48366699 0.59851988]
 [0.42396133 0.1394344  0.4898589  0.74307941]
 [0.73498962 0.09622179 0.14326123 0.87234939]
 [0.26618049 0.50924503 0.65145571 0.4699903 ]]
<class 'numpy.matrix'>


### 2.mat创建常见的矩阵

In [4]:
import numpy as np
 
# 创建一个3*3的零矩阵，矩阵这里zeros函数的参数是一个tuple类型（3,3）
data1 = np.mat(np.zeros((3,3)))
print(data1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# 创建一个2*4的1矩阵，默认是浮点型的数据，如果需要时int，可以使用dtype=int
data2 = np.mat(np.ones((2,4)))
print(data2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# 这里使用numpy的random模块
# random.rand(2,2)创建的是一个二维数组，但是需要将其转化为matrix
data3 = np.mat(np.random.rand(2,2))
print(data3)

[[0.57507547 0.90096564]
 [0.7172608  0.51678673]]


In [7]:
# 生成一个3*3的0-10之间的随机整数矩阵，如果需要指定下界可以多加一个参数
data4  = np.mat(np.random.randint(10,size=(3,3)))
print(data4)

[[1 2 4]
 [9 2 9]
 [2 3 3]]


In [8]:
# 产生一个2-8之间的随机整数矩阵
data5 = np.mat(np.random.randint(2,8,size=(2,5)))
print(data5)

[[3 2 5 4 6]
 [3 5 4 6 7]]


In [9]:
# 产生一个2*2的对角矩阵
data6 = np.mat(np.eye(2,2,dtype=int))
print(data6)

[[1 0]
 [0 1]]


In [10]:
# 生成一个对角线为1,2,3的对角矩阵
a1 = [1,2,3]
a2 = np.mat(np.diag(a1))

### 3.full  
`numpy.full(shape,fill_value=num)`用于创建一个自定义形状的数组,可以自己指定一个值,用它填满整个数组。
`fill_value` 用来填充的值，可以是数字，也可以是字符串

In [11]:
nd_test = np.full(shape=(2,3,1),fill_value='ai')
print(nd_test)

[[['ai']
  ['ai']
  ['ai']]

 [['ai']
  ['ai']
  ['ai']]]


### 4.nonzero()  
`nonzero`函数是`numpy`中用于得到数组`array`中非零元素的位置（数组索引）函数。它的返回值是一个长度为`a.ndim`（数组a的轴数）的元组，元组的每个元素都是一个整数数组，其值为非零元素的下标在对应轴上的值。只有a中非零元素才会有索引值，那些零值元素没有索引值

In [12]:
import numpy as np
a = [0,1,2]
b = np.nonzero(a)
b

(array([1, 2]),)

In [13]:
np.array(b).ndim

2

In [14]:
c = array([[1,1,1,0,1,1],[1,1,1,0,1,0],[1,1,1,0,1,1]])
print(c)
d = nonzero(c)
print(d)

[[1 1 1 0 1 1]
 [1 1 1 0 1 0]
 [1 1 1 0 1 1]]
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 2]), array([0, 1, 2, 4, 5, 0, 1, 2, 4, 0, 1, 2, 4, 5]))


In [15]:
b2 = np.array([[True,False,True],[True,False,False]])
res2 = np.nonzero(b2)

In [16]:
res2

(array([0, 0, 1]), array([0, 2, 0]))

### 5 矩阵运算

In [17]:
#矩阵相乘就是矩阵的乘法操作，要求左边矩阵的列和右边矩阵的行数要一致
from numpy import  *
''' 1*2 的矩阵乘以2*1 的矩阵  得到1*1 的矩阵'''
 
a1 = mat([1,2])
print(a1)
a2 = mat([[1],[2]])
print(a2)
a3 = a1*a2
print(a3)

[[1 2]]
[[1]
 [2]]
[[5]]


In [18]:
#矩阵点乘则要求矩阵必须维数相等，即M*N维矩阵乘以M*N维矩阵
from numpy import  *
''' 矩阵点乘为对应矩阵元素相乘'''
 
a1 = mat([1,1])
print(a1)
a2 = mat([2,2])
print(a2)
a3 = multiply(a1,a2)
print(a3)

[[1 1]]
[[2 2]]
[[2 2]]


In [19]:
a1 = mat([2,2])
a2 = a1*2
print(a2)

[[4 4]]


In [20]:
from numpy import *
''' 矩阵求逆变换:求矩阵matrix([[0.5,0],[0,0.5]])的逆矩阵'''
 
a1 = mat(eye(2,2)*0.5)
print(a1)
a2 = a1.I
print(a2)

[[0.5 0. ]
 [0.  0.5]]
[[2. 0.]
 [0. 2.]]


In [21]:
from numpy import *
'''矩阵的转置'''
 
a1 = mat([[1,1],[0,0]])
print(a1)
a2 = a1.T
print(a2)

[[1 1]
 [0 0]]
[[1 0]
 [1 0]]


In [22]:
from numpy import *
'''计算每一列，行的和'''
 
a1 = mat([[1,1],[2,3],[4,5]])
print(a1)
#  列和，这里得到的是1*2的矩阵
a2=a1.sum(axis=0)
print(a2)

[[1 1]
 [2 3]
 [4 5]]
[[7 9]]


In [23]:
#  行和，这里得到的是3*1的矩阵
a3=a1.sum(axis=1)
print(a3)

[[2]
 [5]
 [9]]


In [24]:
#  计算第一行所有列的和，这里得到的是一个数值
a4=sum(a1[1,:])
print(a4)

5


### np.tile(A, reps)

In [25]:
a = np.array([0, 1, 2])
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

In [26]:
np.tile(a, (2, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

In [27]:
b = np.array([[1, 2], [3, 4]])

In [28]:
np.tile(b, 2)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])

In [29]:
np.tile(b, (2, 1))

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [30]:
c = np.array([1,2,3,4])

In [31]:
np.tile(c,(4,1))

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

### numpy范数用法

### numpy.save  
保存一个数组到一个二进制的文件中，保存格式是.npy

In [33]:
import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.save('save_x',x) #数据保存

In [36]:
np.load('save_x.npy') #获取保存的数据

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### np.savez  
这个同样是保存数组到一个二进制的文件中，但是厉害的是，它可以保存多个数组到同一个文件中，保存格式为.npz，它们其实就是多个前面np.save的保存的npy，再通过打包（未压缩）的方式把这些文件归到一个文件上，不行你再去解压npz文件就知道自己保存的是多个npy

In [37]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
y=np.sin(x)
y

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [55]:
np.savez('save_xy',x=x,y=y)

In [56]:
#读取保存的数据
npzfile=np.load('save_xy.npz') #是一个对象,无法读取

In [57]:
npzfile

In [58]:
npzfile=np.load('save_xy.npz')

In [59]:
npzfile['x']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
npzfile['y']

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

在深度学习中，我们保存了训练集，验证集，测试集，还包括它们的标签，用这个方式存储起来，要加载什么有什么，文件数量大大减少，也不会到处改文件名。

### np.savetxt()  
以简单文本文件格式存储和获取数组数据，通过savetxt()和loadtxt()函数来完成的。

In [61]:
a = np.array([1,2,3,4,5])
np.savetxt('out.txt',a)
b = np.loadtxt('out.txt')
print(b)

[1. 2. 3. 4. 5.]


## ndarray数组  
Numpy中定义的最重要的对象是成为ndarray的N维数组类型。它描述相同类型的元素集合。可以使用基于零的索引访问集合中的项目。

数组的维数称为秩，简单来说就是如果你需要获取数组中一个特定元素所需的坐标数，如a是一个2×3×4的矩阵，你索引其中的一个元素必须给定三个坐标a[x,y,z]，故它的维数就是3。

　　我们可以直接将数组看作一种新的数据类型，就像list、tuple、dict一样，但数组中所有元素的类型必须是一致的，Python支持的数据类型有整型、浮点型以及复数型，但这些类型不足以满足科学计算的需求，因此NumPy中添加了许多其他的数据类型，如bool、inti、int64、float32、complex64等。同时，它也有许多其特有的属性和方法。
  
### ndarray属性

In [62]:
a = [1,2,3,4,5,6]
# 将列表转换为数组
b = np.array(a)

In [63]:
b

array([1, 2, 3, 4, 5, 6])

In [64]:
b.size

6

In [65]:
b.shape

(6,)

In [66]:
b.ndim

1

In [67]:
b.dtype

dtype('int64')

In [68]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [70]:
b = np.array([[1, 2], [3, 4]])
b

array([[1, 2],
       [3, 4]])

In [71]:
a = np.array([1,  2,  3,4,5], ndmin =  2)
print(a)

[[1 2 3 4 5]]


In [72]:
a = np.array([1,  2,  3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


### ndarray方法

In [73]:
#np.reshape
a = np.arange(8)
print('原始数组：')
print(a)
print('\n')
 
b = a.reshape(4,2)
print('修改后的数组：')
print(b)

原始数组：
[0 1 2 3 4 5 6 7]


修改后的数组：
[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [74]:
#np.ndarray.flatten
import numpy as np
a = np.arange(8).reshape(2,4)
 
print('原数组：')
print(a)
print('\n')
# default is column-major
 
print('展开的数组：')
print(a.flatten())
print('\n')
 
print('以 F 风格顺序展开的数组：')
print(a.flatten(order = 'F'))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


展开的数组：
[0 1 2 3 4 5 6 7]


以 F 风格顺序展开的数组：
[0 4 1 5 2 6 3 7]


In [75]:
#np.ravel
import numpy as np
a = np.arange(8).reshape(2,4)
 
print('原数组：')
print(a)
print('\n')
 
print('调用 ravel 函数之后：')
print(a.ravel())
print('\n')
 
print('以 F 风格顺序调用 ravel 函数之后：')
print(a.ravel(order = 'F'))

原数组：
[[0 1 2 3]
 [4 5 6 7]]


调用 ravel 函数之后：
[0 1 2 3 4 5 6 7]


以 F 风格顺序调用 ravel 函数之后：
[0 4 1 5 2 6 3 7]


通过arange生成的序列就不是简简单单的列表类型了，而是一个一维数组。

如果一维数组不是一个规律的有序元素，而是人为的输入，就需要array()函数创建了

In [81]:
arr1 = np.array((1,20,13,28,22))

In [82]:
arr1

array([ 1, 20, 13, 28, 22])

In [83]:
type(arr1)

numpy.ndarray

上面是由元组序列构成的一维数组。

In [84]:
arr2 = np.array([1,1,2,3,5,8,13,21])
arr2

array([ 1,  1,  2,  3,  5,  8, 13, 21])

In [85]:
type(arr2)

numpy.ndarray

上面是由列表序列构成的一维数组

### 二维数组的创建

In [86]:
arr3 = np.array(((1,1,2,3),(5,8,13,21),(34,55,89,144)))
arr3

array([[  1,   1,   2,   3],
       [  5,   8,  13,  21],
       [ 34,  55,  89, 144]])

In [87]:
arr4 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr4

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
np.empty([3,4]) #返回3×4二维空数组

array([[4.67063066e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000]])

In [89]:
p=np.identity(4)

In [90]:
p

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### ones_like, zero_like, empty_like

In [91]:
a=np.array([[[1,2],[1,2]],[[1,2],[1,2]],[[1,2],[1,2]]])
a.shape

(3, 2, 2)

In [92]:
b = np.ones_like(a)

In [93]:
b

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [95]:
b=np.zeros_like(a) #empty_like原理相同
b

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

### np.power(x1, x2)

In [96]:
x1 = range(6)
x1

range(0, 6)

In [97]:
np.power(x1, 3)

array([  0,   1,   8,  27,  64, 125])

In [98]:
x2 = [1.0, 2.0, 3.0, 3.0, 2.0, 1.0]
np.power(x1, x2)

array([ 0.,  1.,  8., 27., 16.,  5.])

In [99]:
x2 = np.array([[1, 2, 3, 3, 2, 1], [1, 2, 3, 3, 2, 1]])
x2

array([[1, 2, 3, 3, 2, 1],
       [1, 2, 3, 3, 2, 1]])

In [100]:
np.power(x1, x2)

array([[ 0,  1,  8, 27, 16,  5],
       [ 0,  1,  8, 27, 16,  5]])

### np.unique()  
该函数是去除数组中的重复数字，并进行排序之后输出

In [101]:
a = [2,3,4,1,21,32,32,32,2,1]
c = [[1,2,3],[1,2,3],[2,3,4]]
resa = np.unique(a)
resc = np.unique(c)
resa

array([ 1,  2,  3,  4, 21, 32])

In [102]:
resc

array([1, 2, 3, 4])

### np.argsort()
返回的是数组值从小到达的索引值

In [103]:
# One dimensional array:一维数组
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0])

In [104]:
#Two-dimensional array:二维数组
x = np.array([[0, 3], [2, 2]])
x

array([[0, 3],
       [2, 2]])

In [105]:
np.argsort(x, axis=0) #按列排序

array([[0, 1],
       [1, 0]])

In [106]:
np.argsort(x, axis=1) #按行排序

array([[0, 1],
       [0, 1]])

### np.column_stack()

In [108]:
a = np.array((1, 2, 3))
b = np.array((2, 3, 4))
c = np.column_stack((a, b))
c

array([[1, 2],
       [2, 3],
       [3, 4]])

In [109]:
a = np.array(((1, 2, 3), (4, 3, 2)))
b = np.array(((2,3,4),(2,12,2)))
c = np.column_stack((a,b))
c

array([[ 1,  2,  3,  2,  3,  4],
       [ 4,  3,  2,  2, 12,  2]])

In [111]:
#创建正态分布随机数数组,mean=2,std=3
samples = np.random.normal(2,3,size=(4,4))
samples

array([[ 2.48853212,  4.1981142 ,  2.4443572 ,  0.62647732],
       [ 8.27160198,  2.51852011,  6.53536688, -1.540713  ],
       [ 1.15803825,  7.4611584 ,  3.06826534, -4.16592115],
       [ 8.15490514,  4.85768789,  1.84721736, -2.78789756]])

In [112]:
#创建标准正态分布数组
samples1 = np.random.randn(4,4)
samples

array([[ 2.48853212,  4.1981142 ,  2.4443572 ,  0.62647732],
       [ 8.27160198,  2.51852011,  6.53536688, -1.540713  ],
       [ 1.15803825,  7.4611584 ,  3.06826534, -4.16592115],
       [ 8.15490514,  4.85768789,  1.84721736, -2.78789756]])

In [113]:
#创建随机整数数组
draws = np.random.randint(0,10,size=(3,4))
draws

array([[2, 6, 9, 8],
       [2, 8, 8, 2],
       [4, 7, 4, 9]])

In [114]:
arr = np.arrar = np.array([[1,2,3],[4,5,6]],dtype=np.float32)
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

### 数组转置和轴对称

In [116]:
arr = np.arange(15).reshape((5,3))
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [117]:
arr.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [119]:
arr = np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [120]:
arr.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [121]:
arr.swapaxes(1,2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])

### np.where

In [122]:
xarr = np.array([1.1,1.2,1.3,1.4,1.5])
np.where(xarr>1.2,2,-2)

array([-2, -2,  2,  2,  2])

### cumsum累加计算 cumprod累积计算

In [124]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
arr.cumsum(0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [126]:
arr.cumprod(1)

array([[  1,   2,   6],
       [  4,  20, 120],
       [  7,  56, 504]])

### 集合运算函数：
`intersect1d(x,y)` 用于计算x和y的公共结果，并返回有序结果,交集  
`union1d(x,y)` 用于计算x和y的并集，并返回有序结果,并集    
`setdiff1d(x,y)`,集合的差，即元素在x中不在y中,差集    

In [127]:
x = np.array([1,2,4,5])
y = np.array([3,4,5])
np.intersect1d(x,y)

array([4, 5])

In [128]:
np.union1d(x,y)

array([1, 2, 3, 4, 5])

In [129]:
np.setdiff1d(x,y)

array([1, 2])

### 线性代数 

In [130]:
#矩阵的乘积
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[6,23],[-1,7],[8,9]])
np.dot(x,y)

array([[ 28,  64],
       [ 67, 181]])

In [131]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [132]:
y

array([[ 6, 23],
       [-1,  7],
       [ 8,  9]])

In [134]:
#计算矩阵的逆
from numpy.linalg import inv,det,eig,qr,svd
t = np.array([[1,2,3],[2,3,4],[4,5,6]])

In [137]:
#计算矩阵行列式
det(t)

0.0

In [138]:
#计算QR分解值
qr(t)

(array([[-0.21821789, -0.81649658, -0.53452248],
        [-0.43643578, -0.40824829,  0.80178373],
        [-0.87287156,  0.40824829, -0.26726124]]),
 array([[-4.58257569, -6.11010093, -7.63762616],
        [ 0.        , -0.81649658, -1.63299316],
        [ 0.        ,  0.        ,  0.        ]]))

In [139]:
#计算奇异值分解值svd
svd(t)

(array([[-0.33735892, -0.77490301, -0.53452248],
        [-0.49235751, -0.33871366,  0.80178373],
        [-0.80235469,  0.53366505, -0.26726124]]),
 array([1.09222648e+01, 8.39125544e-01, 2.97297986e-16]),
 array([[-0.41488581, -0.56431188, -0.71373795],
        [ 0.81314396,  0.12200588, -0.56913221],
        [ 0.40824829, -0.81649658,  0.40824829]]))

In [140]:
#计算特征值和特征向量
eig(t)

(array([ 1.08309519e+01, -8.30951895e-01,  1.01486082e-16]),
 array([[ 0.34416959,  0.72770285,  0.40824829],
        [ 0.49532111,  0.27580256, -0.81649658],
        [ 0.79762415, -0.62799801,  0.40824829]]))

### np.linspace()  
下例中创建一个0~1间隔为1/9的行向量（按等差数列形式生成），从0开始，包括1.

In [144]:
np.linspace(0, 1, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

### np.fromfunction()  
生成9\*9乘法表

In [146]:
def func(i, j):
    return (i+1)*(j+1)
np.fromfunction(func,(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])