### 1.数组的创建
二维数组创建：传入一个嵌套list即可

In [2]:
import numpy as np
np.array([[1, 2, 3],[4, 5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
arr3 = np.array(((1,1,2,3),(5,8,13,21),(34,55,89,144)))

In [15]:
arr3

array([[  1,   1,   2,   3],
       [  5,   8,  13,  21],
       [ 34,  55,  89, 144]])

通过arange创建数组：下例中创建一个0~1间隔为0.1的行向量，从0开始，不包括1

In [3]:
np.arange(0,1,0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

通过对齐广播方式生成一个多维的数组。
![](https://github.com/weiweia92/pictures/blob/master/Screenshot%20from%202020-07-29%2011-57-39.png)

In [4]:
A = np.arange(1,60,10)

In [5]:
A

array([ 1, 11, 21, 31, 41, 51])

In [6]:
A.reshape(-1,1)

array([[ 1],
       [11],
       [21],
       [31],
       [41],
       [51]])

In [7]:
np.arange(0,6)

array([0, 1, 2, 3, 4, 5])

In [8]:
np.arange(1,60,10).reshape(-1,1) + np.arange(0,6)

array([[ 1,  2,  3,  4,  5,  6],
       [11, 12, 13, 14, 15, 16],
       [21, 22, 23, 24, 25, 26],
       [31, 32, 33, 34, 35, 36],
       [41, 42, 43, 44, 45, 46],
       [51, 52, 53, 54, 55, 56]])

通过linspace函数创建数组：下例中创建一个0~1间隔为1/9的行向量（按等差数列形式生成），从0开始，包括1.

In [9]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

通过logspace函数创建数组：下例中创建一个1~100，有20个元素的行向量（按等比数列形式生成），其中0表示10^0=1，2表示10^2=100，从1开始，包括100

In [12]:
np.logspace(0,2,20)

array([  1.        ,   1.27427499,   1.62377674,   2.06913808,
         2.6366509 ,   3.35981829,   4.2813324 ,   5.45559478,
         6.95192796,   8.8586679 ,  11.28837892,  14.38449888,
        18.32980711,  23.35721469,  29.76351442,  37.92690191,
        48.32930239,  61.58482111,  78.47599704, 100.        ])

通过frombuffer，fromstring，fromfile和fromfunction等函数从字节序列、文件等创建数组，下例中生成一个9*9乘法表

In [16]:
def func(i, j):
    return (i+1)*(j+1)

In [17]:
np.fromfunction(func,(9,9))

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 4.,  8., 12., 16., 20., 24., 28., 32., 36.],
       [ 5., 10., 15., 20., 25., 30., 35., 40., 45.],
       [ 6., 12., 18., 24., 30., 36., 42., 48., 54.],
       [ 7., 14., 21., 28., 35., 42., 49., 56., 63.],
       [ 8., 16., 24., 32., 40., 48., 56., 64., 72.],
       [ 9., 18., 27., 36., 45., 54., 63., 72., 81.]])

当使用布尔数组b作为下标存取数组x中的元素时，将收集数组x中所有在数组b中对应下标为True的元素。

In [18]:
x = np.arange(5,0,-1)
print(x)
#通过一个bool型的array进行索引
print(x[np.array([True, False, True, False, False])])

[5 4 3 2 1]
[5 3]


利用条件进行索引：利用不等式等进行索引

In [19]:
x = np.arange(0,10)
print(x[x>5])

[6 7 8 9]


### !Note

In [69]:
scores = np.array([4, 7, 1, 2, 4, 3, 2, -2, 3, 5, -1, 7]).reshape(-1,4)

In [70]:
scores  # y=2

array([[ 4,  7,  1,  2],
       [ 4,  3,  2, -2],
       [ 3,  5, -1,  7]])

In [71]:
scores[2,2]

-1

In [72]:
scores[range(0,3), 2]

array([ 1,  2, -1])

In [73]:
scores[range(0,3), 2].shape

(3,)

In [74]:
scores[range(0,3), 2].reshape(-1,1)

array([[ 1],
       [ 2],
       [-1]])

In [75]:
scores[range(0,3), 2].reshape(-1,1).shape

(3, 1)

In [76]:
scores - scores[range(0,3), 2].reshape(-1,1) + 1

array([[ 4,  7,  1,  2],
       [ 3,  2,  1, -3],
       [ 5,  7,  1,  9]])

In [79]:
scores[range(0,3), 2] = 0

In [80]:
scores

array([[ 4,  7,  0,  2],
       [ 4,  3,  0, -2],
       [ 3,  5,  0,  7]])

In [81]:
scores = (scores > 0)*scores

In [82]:
scores

array([[4, 7, 0, 2],
       [4, 3, 0, 0],
       [3, 5, 0, 7]])

In [84]:
scores.sum() / 3

11.666666666666666

### np.random.choice
从0-4的数字中，随机选取一个数字，我们以往的随机数都是等概率的随机生成，在这个，我们为每个数字一个随机的概率大小，就是生成0的概率为0.1,1的概率为0.3，...，4的概率为0.1。所有choice就是以一定的概率随机生成一个数字或者几个数字（数组）

`numpy.random.choice(a, size=None, replace=True, p=None)`  
- replace=True:采样的元素会有重复,False:不重复

In [ ]:
np.random.choice(5, 1, p=[0.1, 0.3, 0.2, 0.3, 0.1])