### masked_fill(mask, value) -> Tensor

In [1]:
import torch
data = torch.randn(2, 3)
data

tensor([[ 1.6143,  0.5116,  0.8156],
        [ 0.4156, -0.9350,  0.4946]])

In [2]:
mask = torch.tensor([[True, False, True], [False, True, False]])
mask

tensor([[ True, False,  True],
        [False,  True, False]])

In [3]:
masked1 = data.masked_fill(mask, 999)
masked1

tensor([[9.9900e+02, 5.1159e-01, 9.9900e+02],
        [4.1559e-01, 9.9900e+02, 4.9458e-01]])

In [4]:
data

tensor([[ 1.6143,  0.5116,  0.8156],
        [ 0.4156, -0.9350,  0.4946]])

### masked_fill_(mask, value)

In [5]:
data1 = data
data1

tensor([[ 1.6143,  0.5116,  0.8156],
        [ 0.4156, -0.9350,  0.4946]])

In [6]:
masked2 = data1.masked_fill_(mask, 999)
masked2

tensor([[9.9900e+02, 5.1159e-01, 9.9900e+02],
        [4.1559e-01, 9.9900e+02, 4.9458e-01]])

In [7]:
data1

tensor([[9.9900e+02, 5.1159e-01, 9.9900e+02],
        [4.1559e-01, 9.9900e+02, 4.9458e-01]])

### -np.inf

In [8]:
import numpy as np
masked3 = data.masked_fill(mask, -np.inf)
masked3

tensor([[  -inf, 0.5116,   -inf],
        [0.4156,   -inf, 0.4946]])