# Lesson 2 张量的索引，分片，合并以及维度调整

张量作为有序的序列，也是具备数据索引的功能，并且基本索引方法和Python原生的列表，NumPy中的数组基本一致，当然所不同的是PyTorch还定义了一种采用函数来进行索引的方式。

而作为PyTorch中基本数据类型，张量即具备了列表，数组的基本功能，同时还充当了向量，矩阵甚至数据框等重要数据结构，因此PyTorch中设置了非常完备的张量合并与变换的操作。

In [1]:
import torch
import numpy as np

## 一.张量的符号索引

张量也是**有序序列**，我们可以根据每个元素在系统内的顺序编号，来找出特定的元素，也就是索引。

### 1.一维张量索引

一维张量的索引过程和Python原生对象类型的索引一致，基本格式遵循`[start:end:step]`

In [3]:
t1 = torch.arange(1, 11)
t1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* 从左到右，从零开始

In [4]:
t1[0]

tensor(1)

In [5]:
t1[0].item()

1

**注：张量的索引出来的结果还是零维张量，而不是单独的数，要转化成单独的数需要使用`item()`方法**

* 冒号分割，表示对某个区域进行索引——切片

In [6]:
t1[1:8]  #左闭右开区间

tensor([2, 3, 4, 5, 6, 7, 8])

In [7]:
t1[1:8:2]   #第二个冒号表示索引的间隔

tensor([2, 4, 6, 8])

* 冒号前后没有值，表示索引这个区域

In [8]:
t1[1::2]  #从第二个元素开始索引，一直到结尾，并且每隔两个数取一个

tensor([ 2,  4,  6,  8, 10])

In [9]:
t1[:8:2]  #从第一个元素开始索引到第九个元素（不包含），并且每隔2个数取一个

tensor([1, 3, 5, 7])

**张量索引中，step位必须大于0**

In [10]:
t1[9:1:-1]

ValueError: step must be greater than zero

### 2.二维张量索引

二维张量的索引逻辑和一维张量的索引逻辑基本相同，二维张量可以视为两个一维张量组合而成，而在实际的索引过程中，需要用逗号进行分隔，分别表示对哪个一维张量进行索引，以及具体的一维张量的索引。

In [13]:
t2 = torch.arange(1, 10).reshape(3,3)
t2

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [14]:
t2[0, 1]

tensor(2)

In [15]:
t2[0, ::2]   #表示索引第一行，对于列，每隔两个元素取一个

tensor([1, 3])

In [16]:
t2[0, [0, 2]]

tensor([1, 3])

In [17]:
t2[::2, ::2]  #对于行和列均为每隔两个元素取一个

tensor([[1, 3],
        [7, 9]])

In [18]:
t2[[0, 2], 1]  #取第一行第三行，第二列元素

tensor([2, 8])

理解：对于二维张量，基本可以视为对矩阵的索引，并且行列的索引遵照相同的索引规范，并且用逗号进行分隔

### 3.三维张量的索引

在二维张量索引的基础上，三维张量拥有三个索引的维度，我们将三维张量视为矩阵组成的序列。在实际索引过程中拥有三个维度，分别为索引矩阵，索引矩阵的行，索引矩阵的列。

In [19]:
t3 = torch.arange(1, 28).reshape(3, 3, 3)
t3

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9]],

        [[10, 11, 12],
         [13, 14, 15],
         [16, 17, 18]],

        [[19, 20, 21],
         [22, 23, 24],
         [25, 26, 27]]])

In [20]:
t3[1, 1, 1]  #第二个索引矩阵中第二个行第二列元素

tensor(14)

In [21]:
t3[1, ::2, ::2]

tensor([[10, 12],
        [16, 18]])

In [22]:
t3[::2,::2,::2]

tensor([[[ 1,  3],
         [ 7,  9]],

        [[19, 21],
         [25, 27]]])

理解：更为本质的角度去理解高维张量的索引，其实就是围绕张量的‘形状’进行索引

In [23]:
t3.shape

torch.Size([3, 3, 3])

In [24]:
t3[1, 1, 1]

tensor(14)

## 二.张量的函数索引

在PyTorch中，我们还可以使用`index_select`函数，通过指定`index`对张量进行索引

In [25]:
t1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [26]:
t1.ndim

1

In [27]:
indices = torch.tensor([1, 2])

In [28]:
indices

tensor([1, 2])

In [29]:
torch.index_select(t1, 0, indices)

tensor([2, 3])

在`index_select`函数中，第二个参数实际上代表的是索引的维度，对于t1这个一维向量来说，由于只有一个维度，因此第二个参数取值为0，就代表在第一个维度上进行索引

In [30]:
t2 = torch.arange(12).reshape(4, 3)
t2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [31]:
t2.shape

torch.Size([4, 3])

In [32]:
indices

tensor([1, 2])

dim参数取值为0，代表在shape的第一个维度上索引

In [33]:
torch.index_select(t2, 0, indices)

tensor([[3, 4, 5],
        [6, 7, 8]])

dim参数取值为1，代表在shape的第二个维度上索引

In [34]:
torch.index_select(t2, 1, indices)

tensor([[ 1,  2],
        [ 4,  5],
        [ 7,  8],
        [10, 11]])

## 三.tensor.view()方法

在正式介绍张量的切片方法之前，需要先介绍PyTorch中的`.view()`方法。该方法会返回一个类似视图的结果，该结果和原张量对象共享一块数据存储空间，并且通过`.view()`方法，还可以改变对象结构，生成一个不同结构，但共享一个存储空间的张量。当然，共享一个存储空间，也就代表二者是‘浅拷贝’的关系，修改其中一个，另一个也会同步进行更改。

In [35]:
t = torch.arange(6).reshape(2, 3)
t

tensor([[0, 1, 2],
        [3, 4, 5]])

In [36]:
te = t.view(3, 2)   #构建一个数据相同，但形状不同的"视图"
te

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [37]:
t

tensor([[0, 1, 2],
        [3, 4, 5]])

In [38]:
t[0] = 1

In [39]:
t

tensor([[1, 1, 1],
        [3, 4, 5]])

In [40]:
te     #同步变化

tensor([[1, 1],
        [1, 3],
        [4, 5]])

In [41]:
tr = t.view(1, 2, 3)   #维度也可以修改
tr

tensor([[[1, 1, 1],
         [3, 4, 5]]])

"视图"的作用就是节省空间，值得注意的是，在接下来介绍的很多切分张量的方法中，返回的都是“视图”，而不是新生成一个对象

## 四.张量的分片函数

### 1.分块：chunk 函数

chunk函数能够按照某维度，对张量进行均匀切分，并且返回结果是原张量的视图

In [42]:
t2 = torch.arange(12).reshape(4, 3)
t2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [43]:
tc = torch.chunk(t2, 4, dim=0)   #在第零维上(按行)进行四等分

In [44]:
tc    #元组

(tensor([[0, 1, 2]]),
 tensor([[3, 4, 5]]),
 tensor([[6, 7, 8]]),
 tensor([[ 9, 10, 11]]))

In [45]:
tc[0][0]

tensor([0, 1, 2])

In [46]:
tc[0][0][0] = 1

In [47]:
tc

(tensor([[1, 1, 2]]),
 tensor([[3, 4, 5]]),
 tensor([[6, 7, 8]]),
 tensor([[ 9, 10, 11]]))

In [48]:
t2

tensor([[ 1,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

当原张量不能均分时，chunk不会报错，但会返回其他均分的结果

In [49]:
torch.chunk(t2, 3, dim=0)

(tensor([[1, 1, 2],
         [3, 4, 5]]),
 tensor([[ 6,  7,  8],
         [ 9, 10, 11]]))

In [50]:
len(torch.chunk(t2, 3, dim=0))

2

In [51]:
torch.chunk(t2, 5, dim=0)  #返回次一级的均分结果

(tensor([[1, 1, 2]]),
 tensor([[3, 4, 5]]),
 tensor([[6, 7, 8]]),
 tensor([[ 9, 10, 11]]))

### 2.拆分：split函数

split既能进行均分，也能进行自定义切分。当然，要注意的是，和chunk函数一样，split返回结果也是view.

In [53]:
t2 = torch.arange(12).reshape(4, 3)
t2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

均分情况

In [54]:
torch.split(t2, 2, 0)  #第二个参数只输入一个数值时表示均分，第三个参数表示进行的维度（0:按行）

(tensor([[0, 1, 2],
         [3, 4, 5]]),
 tensor([[ 6,  7,  8],
         [ 9, 10, 11]]))

In [55]:
torch.split(t2, [1, 3], 0)

(tensor([[0, 1, 2]]),
 tensor([[ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]]))

注意：当第二个参数位输入一个序列时，序列的各数值的和必须等于对应维度下形状分量的取值。例如，上述代码中，按照第一个维度进行切分，而t2总共有4行，因此序列的求和必须等于4，也就是1+3=4，而序列中每个分量的取值则代表切块大小。

In [58]:
torch.split(t2, [1, 1, 1, 1], 0)

(tensor([[0, 1, 2]]),
 tensor([[3, 4, 5]]),
 tensor([[6, 7, 8]]),
 tensor([[ 9, 10, 11]]))

In [59]:
torch.split(t2, [1, 1, 2], 0)

(tensor([[0, 1, 2]]),
 tensor([[3, 4, 5]]),
 tensor([[ 6,  7,  8],
         [ 9, 10, 11]]))

In [60]:
ts = torch.split(t2, [1, 2], 1)

In [61]:
ts

(tensor([[0],
         [3],
         [6],
         [9]]),
 tensor([[ 1,  2],
         [ 4,  5],
         [ 7,  8],
         [10, 11]]))

In [62]:
ts[0][0] = 1 #view进行修改

In [63]:
t2           #原对象同步改变

tensor([[ 1,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

tensor的split方法和array的split方法有很大的区别，array的split方法时根据索引进行切分。

## 五.张量的合并操作

张量的合并操作类似于列表的追加元素，可以拼接也可以堆叠

* 拼接函数：`cat`

In [64]:
a = torch.zeros(2, 3)
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [66]:
b = torch.ones(2, 3)
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [67]:
c = torch.zeros(3, 3)
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [68]:
torch.cat([a, b])  #按照行进行拼接，dim默认取值为0

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [69]:
torch.cat([a, b], 1) #按照列进行拼接

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])

In [70]:
torch.cat([a, c], 1)  #形状不匹配时将报错

RuntimeError: Sizes of tensors must match except in dimension 1. Got 2 and 3 in dimension 0 (The offending index is 1)

**注意：拼接的本质时实现元素的堆积，也就是构成a, b两个二维张量的各一维张量的堆积，最终还是构成二维向量**

* 堆叠函数：`stack`

和拼接不同，堆叠不是将元素拆分重装，而是简单的将各参与堆叠的对象分装到一个更高维度的张量里。

In [71]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [72]:
b

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [73]:
torch.stack([a, b])  #堆叠之后生成一个三维张量

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [74]:
torch.stack([a, b]).shape

torch.Size([2, 2, 3])

In [76]:
torch.cat([a, b]).shape

torch.Size([4, 3])

注意对比二者区别，拼接之后维度不变，堆叠之后维度升高。拼接是把一个个元素单独提取出来之后再放到二维张量中，而堆叠则是直接将两个二维张量封装到一个三维张量中，因此堆叠的要求更高，参与堆叠的张量必须形状完全相同。

In [77]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [78]:
c

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [79]:
torch.cat([a, c])   #横向拼接时，对行数没有一致性要求

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [80]:
torch.stack([a, c])  #维数不匹配报错

RuntimeError: stack expects each tensor to be equal size, but got [2, 3] at entry 0 and [3, 3] at entry 1

## 六.张量维度变换

通过reshape方法能够灵活调整张量的形状，而在实际操作张量进行计算时，往往需要另外进行降维和升维操作，当我们需要除去不必要的维度时，可以使用`squeeze`函数。而需要手动升维时，则可采用`unsqueeze`函数。

* `squeeze`函数：删除不必要的维度

In [84]:
a = torch.arange(4)
a

tensor([0, 1, 2, 3])

In [86]:
a2 = a.reshape(1, 4)
a2

tensor([[0, 1, 2, 3]])

In [81]:
t = torch.zeros(1, 1, 3, 1)

In [82]:
t  #一个包含一个三维的四维张量,三维张量包含一个二维矩阵张量（三行一列）

tensor([[[[0.],
          [0.],
          [0.]]]])

In [83]:
t.shape

torch.Size([1, 1, 3, 1])

In [87]:
torch.squeeze(t)

tensor([0., 0., 0.])

In [88]:
torch.squeeze(t).shape

torch.Size([3])

转化后生成了一个一维张量

In [89]:
t1 = torch.zeros(1, 1, 3, 2, 1, 2)
t1.shape

torch.Size([1, 1, 3, 2, 1, 2])

In [90]:
torch.squeeze(t1)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [91]:
torch.squeeze(t1).shape

torch.Size([3, 2, 2])

简单理解，`squeeze`就相当于剔除了shape返回结果中的1

* `unsqeeze`函数：手动升维

In [92]:
t = torch.zeros(1, 2, 1, 2)
t.shape

torch.Size([1, 2, 1, 2])

In [93]:
torch.unsqueeze(t, dim=0)   #在第一个维度索引上升高一个维度

tensor([[[[[0., 0.]],

          [[0., 0.]]]]])

In [94]:
torch.unsqueeze(t, dim=0).shape 

torch.Size([1, 1, 2, 1, 2])

In [95]:
torch.unsqueeze(t, dim=2).shape  #在第3个维度索引上升高一个维度

torch.Size([1, 2, 1, 1, 2])

In [96]:
torch.unsqueeze(t, dim=4).shape   #在第5个维度索引上升高一个维度     

torch.Size([1, 2, 1, 2, 1])