# Lesson1. Tensor(张量)的创建和常用方法

在实际使用PyTorch的过程中，张量对象是我们操作的基本数据类型。

很多时候，在我们没有特别说明什么是深度学习计算框架的时候，我们可以把PyTorch简单看成是Python的深度学习第三方库，在PyTorch中定义了适用于深度学习的基本数据结构——张量，以及张量的各类计算。其实也就相当于NumPy中定义的Array和对应的科学计算方法，正是这些基本数据类型和对应的方法函数，为我们进一步在PyTorch上进行深度学习建模提供了基本对象和基本工具。因此，在正式使用PyTorch进行深度学习建模之前，我们需要熟练掌握PyTorch张量的基本操作。

当然，值得一提的是，张量概念并不是PyTorch独有的，目前看来，基本上通用的深度学习框架都拥有张量这一类数据结构，但不同的深度学习框架中张量的定义和使用方法略有差别。而张量作为数组的衍生概念，其本身的定义和使用方法和NumPy中的Array非常相似，甚至，在复现一些简单的神经网络算法场景中，我们可以直接受用NumPy中的Array来进行操作。当然，并不鼓励大家使用NumPy进行深度学习，因为毕竟NumPy中的Array只提供了很多基本功能，写简单的神经网络尚可，写更复杂的神经网络则会非常复杂，并且Array数据结构本身也不支持GPU运行，因此无法应对工业场景中复杂神经网络背后的大规模数值运算。我们需要知道，工具的差异只会影响实现层的具体表现，因此一方面，我们在学习的过程中，不妨对照NumPy中的Array进行学习，另一方面，我们更需要透过工具的具体功能，来理解和体会背后更深层次的数学原理和算法思想。

In [ ]:
import torch

In [2]:
torch.__version__

'1.8.1'

## 一.张量(Tensor)函数创建方法

张量的最基本创建方法和NumPy中创建Array的格式一致

张量创建函数:`torch.tensor()`   ()内需要是序列-->序列包括列表和元组

In [4]:
t = torch.tensor([1, 2]) #通过列表创建张量
t

tensor([1, 2])

In [5]:
#通过元祖创建张量
torch.tensor((1, 2))

tensor([1, 2])

In [8]:
import numpy as np
a = np.array((1, 2)) #也可以通过元组或列表创建Array
a

array([1, 2])

In [9]:
b = np.array([1, 2])
b

array([1, 2])

In [10]:
#通过数组创建张量
t1 = torch.tensor(a)
t1

tensor([1, 2])

In [11]:
type(t)

torch.Tensor

In [12]:
type(t1)   #type只能区分到tensor级，再往下需要dtype

torch.Tensor

In [14]:
t.dtype   #64位整数型张量对象

torch.int64

In [16]:
a.dtype   #64位整数数组对象

dtype('int64')

In [17]:
np.array([1.1, 2.2]).dtype

dtype('float64')

In [23]:
torch.tensor(np.array([1.11, 2.2])).dtype

torch.float64

In [19]:
t2 = torch.tensor([True, False])   #布尔型张量
t2 

tensor([ True, False])

In [20]:
t2.dtype

torch.bool

通过dtype参数，在创建张量过程中设置输出结果。

In [21]:
# 创建int16整数型张量
torch.tensor([1.1, 2.1], dtype=torch.int16)

<ipython-input-21-2295c7a7075c>:2: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  torch.tensor([1.1, 2.1], dtype=torch.int16)


tensor([1, 2], dtype=torch.int16)

In [22]:
a = torch.tensor(1 + 2j)  # 复数
a

tensor(1.+2.j)

## 二.张量类型的转化

* 张量类型的隐式转化

和Numpy中Array相同，当张量各元素属于不同类型时，系统会自动进行隐式转化

In [24]:
# 浮点型和整数型的隐式转化
torch.tensor([1.1, 2]).dtype

torch.float32

In [25]:
# 布尔型和数值型的隐式转化
torch.tensor([True, 2.0])

tensor([1., 2.])

* 张量类型的转化方法

当然我们还可以使用`.float()`和`.int()`等方法对张量类型进行转化。

**注**：这样的转化是不会改变原来的数据类型的

In [26]:
t

tensor([1, 2])

In [27]:
t.float()

tensor([1., 2.])

In [28]:
# 转化为双精度浮点型
t.double()  

tensor([1., 2.], dtype=torch.float64)

In [30]:
t.dtype   # 不会改变原来的数据类型

torch.int64

In [31]:
# 转化为16位整数
t.short()

tensor([1, 2], dtype=torch.int16)

**由于torch中张量的特殊性(即会把tensor存到GPU上)，因此对于浮点型和整型要比之前的Python的任何原生对象要敏感。对于很多函数来说，对于整数是不支持代入运算的，甚至不会在运算中把整数转化为浮点数。**

对于原生对象可能会存在隐式转换，自动转换类型，但是tensor则不行，需要我们手动转换类型。

## 三.张量的维度和形变

张量作为一组数的结构化表示，也同样拥有维度的概念。简单理解，向量是一维数组，矩阵则是二维数组，以此类推，在张量中，我们可以定义更高维度的数组。当然，张量的高维度数组和NumPy中的高维Array概念类似。

### 1.创建高维张量

* 用简单序列创建一维数组

包含“简单”元素的序列可创建一维数组。

In [32]:
t1

tensor([1, 2])

In [33]:
t1.ndim # 查看张量维度

1

In [34]:
t1.shape #查看形状  torch.Size([2])表示包含两个元素的张量

torch.Size([2])

In [36]:
t1.size()  #和shape函数相同

torch.Size([2])

In [37]:
# 返回拥有几个(N-1)维元素
len(t1)

2

In [38]:
# 返回总共拥有几个数
t1.numel()

2

**注：** 一维张量`len`和`numel`返回结果相同，但更高维度张量则不然。

* 用‘序列’的‘序列’创建二维数组

以此类推，我们还可以用形状相同的序列组成一个新的序列，进而将其转化为二维张量。

In [39]:
# 用list的list创建二维张量
t2 = torch.tensor([[1, 2], [3, 4]])

In [40]:
t2  # 二维张量可以等价于矩阵张量，但是numpy中array则不可以，因为他有np.matrix

tensor([[1, 2],
        [3, 4]])

In [41]:
t2.ndim

2

In [42]:
t2.shape

torch.Size([2, 2])

In [44]:
t2.size()

torch.Size([2, 2])

In [45]:
len(t2)  #此处len函数返回结果代表t2由两个1维张量构成

2

In [46]:
len([[1, 2], [3, 4]])

2

In [47]:
t2.numel()  # 此处numel方法返回的结果表示t2总共由4个数构成

4

* “零”维张量

在PyTorch中，还有一类特殊的张量，被称为零维张量。该类型张量只包含一个元素，但又不是单独一个数。

In [49]:
t0 = torch.tensor([1])  #向量
t0  #一维张量

tensor([1])

In [54]:
t0.ndim

1

In [55]:
t0.shape

torch.Size([1])

In [56]:
t0.size()

torch.Size([1])

In [50]:
t = torch.tensor(1)  #标量
t  #零维张量

tensor(1)

In [51]:
t.ndim

0

In [52]:
t.shape

torch.Size([])

In [53]:
t.size()

torch.Size([])

In [57]:
t.numel()

1

**理解零维张量：**

目前，我们将零维张量视为拥有张量属性的单独一个数。（例如，张量可以存在GPU上，但Python原生数值型对象不行，但零维张量可以，尽管时零维）

从学术名称来说，Python中单独一个数是scalars(标量)，而零维张量则是tensor。

* 高维张量

一般来说，三维及三维以上的张量，我们就将其称为高维张量。当然，在高维张量中最常见的就是三维张量。我们可以将其理解为二维数组或矩阵的集合。

In [58]:
a1 = np.array([[1, 2, 2], [3, 4, 4]])
a1  

array([[1, 2, 2],
       [3, 4, 4]])

In [59]:
a2 = np.array([[5, 6, 6], [7, 8, 8]])
a2 

array([[5, 6, 6],
       [7, 8, 8]])

In [60]:
# 由两个形状相同的二维数组创建一个三维张量
t3 = torch.tensor([a1, a2])
t3

tensor([[[1, 2, 2],
         [3, 4, 4]],

        [[5, 6, 6],
         [7, 8, 8]]])

In [61]:
t3.ndim

3

In [62]:
t3.shape  # 包含两个，两行三列矩阵的张量

torch.Size([2, 2, 3])

In [63]:
len(t3)

2

In [64]:
t3.numel()

12

当然，N维张量的创建方法，我们可以先创建M个N-1维的数组，然后将其拼成一个N维的张量。

### 2.张量的形变

#### 2.1 flatten拉平：将任意维度张量转化成一维张量 

In [65]:
t2

tensor([[1, 2],
        [3, 4]])

In [66]:
t2.flatten()  # 按行排列，拉平

tensor([1, 2, 3, 4])

In [67]:
t3

tensor([[[1, 2, 2],
         [3, 4, 4]],

        [[5, 6, 6],
         [7, 8, 8]]])

In [68]:
t3.flatten()

tensor([1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8])

**注：如果将零维张量flatten,则会将其转化为一维张量**

In [69]:
t

tensor(1)

In [70]:
t.flatten()

tensor([1])

In [72]:
t.flatten().ndim

1

#### 2.2 reshape方法：任意变形

In [73]:
t1

tensor([1, 2])

In [79]:
t1.shape

torch.Size([2])

In [74]:
# 转化为两行，一列的张量
t1.reshape(2, 1)

tensor([[1],
        [2]])

In [77]:
t1.reshape(2, 1).ndim

2

In [78]:
t1.reshape(2, 1).shape

torch.Size([2, 1])

**注：reshape过程中维度的变化：reshape转化后的维度由该方法输入的参数"个数"决定**

* 转化后称为一维张量

In [80]:
t1.reshape(2)

tensor([1, 2])

In [81]:
t1.reshape(2).ndim

1

In [82]:
# 注：另一种表达形式
t1.reshape(2,)

tensor([1, 2])

* 转化生成二维张量

In [83]:
t1

tensor([1, 2])

In [84]:
t1.reshape(1, 2)  #生成包含 一个 两个元素 的二维张量

tensor([[1, 2]])

In [85]:
t1.reshape(1, 2).ndim

2

* 转化后生成三维张量

In [86]:
t1.reshape(1, 1, 2)  # 一个矩阵，并且这个矩阵一行两列矩阵

tensor([[[1, 2]]])

In [87]:
t1.reshape(1, 2, 1)  # 一个矩阵，这个矩阵是两行一列矩阵

tensor([[[1],
         [2]]])

Q1: 如何利用reshape方法，将t3拉平？

In [88]:
t3

tensor([[[1, 2, 2],
         [3, 4, 4]],

        [[5, 6, 6],
         [7, 8, 8]]])

In [90]:
t3.reshape(1, 1, 12)

tensor([[[1, 2, 2, 3, 4, 4, 5, 6, 6, 7, 8, 8]]])

## 四.特殊张量的创建方法

在很多数值科学计算过程中，都会创建一些特殊取值的张量，用于模拟特殊取值的矩阵。如全0矩阵，对角矩阵等。因此PyTorch中也存在很多创建特殊张量的函数。

### 1.特殊取值的张量创建方法

* 全0张量

In [91]:
torch.zeros([2, 3])  # 创建全是0的两行，三列的矩阵张量

tensor([[0., 0., 0.],
        [0., 0., 0.]])

**注：由于zeros已经确定了张量元素的取值，因此该函数传入的参数实际上决定了张量的形状**

* 全1张量

In [92]:
torch.ones([2, 3])

tensor([[1., 1., 1.],
        [1., 1., 1.]])

* 单位矩阵

In [93]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

* 对角矩阵

略有特殊，在PyTorch中，需要利用一维张量去创建对角矩阵

In [94]:
t1

tensor([1, 2])

In [95]:
torch.diag(t1)

tensor([[1, 0],
        [0, 2]])

In [97]:
torch.diag([1, 2]) # 不能使用list直接创建对角矩阵

TypeError: diag(): argument 'input' (position 1) must be Tensor, not list

* rand:服从0-1均匀分布的张量

In [98]:
torch.rand(2, 3)

tensor([[0.2669, 0.2923, 0.6038],
        [0.6084, 0.3236, 0.4538]])

In [100]:
torch.rand([2, 3])

tensor([[0.4786, 0.3014, 0.8626],
        [0.1607, 0.0052, 0.3947]])

* randn:服从标准正态分布的张量

In [99]:
torch.randn(2, 3)

tensor([[ 0.5702, -2.5375,  0.5661],
        [ 0.3809,  1.5170, -0.6475]])

In [101]:
torch.randn([2, 3])

tensor([[-0.9007, -0.4326,  1.1565],
        [ 0.5511,  1.7960, -0.9982]])

* normal:服从指定正态分布的张量

In [102]:
torch.normal(2, 3, size=(2, 3))  # 均值为2，标准差为3的张量

tensor([[3.5125, 1.9359, 2.5171],
        [6.1625, 8.3507, 4.3193]])

In [103]:
torch.normal(2, 3, size=[2, 3])

tensor([[ 1.2287, -3.6193,  3.0511],
        [-1.4252,  3.8556, -0.4287]])

* randint:整数随机采样结果

In [104]:
torch.randint(1, 10, [2, 4]) #在1-10之间随机抽取整数组成两行四列的矩阵张量

tensor([[3, 9, 7, 2],
        [2, 3, 2, 4]])

In [105]:
torch.randint(1, 10, (2, 4))

tensor([[8, 3, 8, 6],
        [8, 9, 9, 4]])

* arange/linspace: 生成数列

In [106]:
torch.arange(5)   #和range相同

tensor([0, 1, 2, 3, 4])

In [107]:
torch.arange(1, 5, 0.5)

tensor([1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000, 4.5000])

In [108]:
torch.linspace(1, 5, 3)   #从1-5(左右都包含)，等距取三个数

tensor([1., 3., 5.])

* empty:生成未初始化的指定形状矩阵

In [109]:
torch.empty(2, 3)

tensor([[1.0533e+21, 1.0739e-05, 1.6519e-04],
        [1.0083e-11, 2.1763e-04, 1.0489e-08]])

* full:根据指定形状，填充指定数值

In [110]:
torch.full([2, 4], 2)

tensor([[2, 2, 2, 2],
        [2, 2, 2, 2]])

In [111]:
torch.full((2, 4), 3)

tensor([[3, 3, 3, 3],
        [3, 3, 3, 3]])

### 2.创建指定形状的数组

当然，我们还能根据指定对象的形状进行数值填充，只需要在上述函数后面加上_like即可。

In [112]:
t1

tensor([1, 2])

In [113]:
t2

tensor([[1, 2],
        [3, 4]])

In [114]:
torch.full_like(t1, 2)  #根据t1形状，填充数值2

tensor([2, 2])

In [116]:
torch.randint_like(t2, 1, 10)

tensor([[1, 4],
        [3, 6]])

In [117]:
torch.zeros_like(t1)

tensor([0, 0])

**需要注意一点：_like类型转化需要注意转化前后数据类型一致的问题**

In [118]:
torch.randn_like(t1) #t1是整数，而转化后变为浮点数，数据类型前后不一致

RuntimeError: "normal_kernel_cpu" not implemented for 'Long'

## 五.张量和其他相关类型之间的转化方法

张量，数组和列表是较为相似的三种类型对象，在实际操作过程中，经常会涉及三种对象的相互转化。在此前张量的创建过程中，我们看到torch.tensor函数可以直接将数组或者列表转化为张量，而我们也可以将张量转化为数组或者列表。

* `.numpy()`方法：张量转化为数组

In [119]:
t1

tensor([1, 2])

In [120]:
t1.numpy()

array([1, 2])

In [121]:
# 当然，也可以通过np.array直接转化为array
np.array(t1)

array([1, 2])

* `.tolist`：张量转化为列表

In [122]:
t1.tolist()

[1, 2]

In [123]:
list(t1)    #构成一维张量的实际上是零维张量

[tensor(1), tensor(2)]

**注意：此时转化的list是由一个个零维张量构成的列表，而非张量的数值组成的列表**

* `.item()`方法：转化为数值

在很多情况下，我们需要将最终计算结果张量转化为单独的数值进行输出，此时需要使用.item方法来执行

In [125]:
n = torch.tensor(1)
n

tensor(1)

In [126]:
n.item()

1

## 六.张量的深拷贝

与Python中其他对象类型一样，等号赋值操作实际上是牵拷贝，需要进行深拷贝，则需要使用clone方法

In [134]:
t1 = torch.arange(10)
t1

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
t11 = t1

In [136]:
t11

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
t1[1]

tensor(1)

In [138]:
t1[1] = 10

In [139]:
t1

tensor([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [140]:
t11

tensor([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])

此处t1和t11二者指向相同的对象。而要使用t11不随t1对象改变而改变，则需要对t11进行深拷贝，从而使得t11单独拥有一份对象

In [141]:
t11 = t1.clone()

In [142]:
t1

tensor([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [143]:
t11

tensor([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])

In [144]:
t1[0]

tensor(0)

In [146]:
t1[0] = 100

In [147]:
t1

tensor([100,  10,   2,   3,   4,   5,   6,   7,   8,   9])

In [148]:
t11

tensor([ 0, 10,  2,  3,  4,  5,  6,  7,  8,  9])